Repository mfdlabs/grid-bot, pull requests merged in 2024-03, with the labels that each got.

#283 Fix SettingsProvidersDefaults link in readme
  README.md
Labels: kind: fix, priority: deliverable, opsec: repo-ops, area: github

#293 #279: Substring error in MessageReceived handler
  shared/events/Events/OnMessage.cs
Labels: kind: fix, priority: key deliverable, platform: linux, opsec: discord-gateway, opsec: we-love-clean-code, area: discord

#294 #292: Do not log thumbnail exceptions
  shared/commands/Modules/Render.cs
  shared/settings/Providers/AvatarSettings.cs
  shared/utility/Implementation/AvatarUtility.cs
  shared/utility/Shared.Utility.csproj
Labels: kind: fix, area: code-ops

#301 Add deployment job
  .github/workflows/deploy.yml
Labels: kind: feature, priority: deliverable, platform: linux, opsec: we-love-clean-code, area: ci-cd, opsec: ci-cd

#304 More configurable parts to the nomad job
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  nomad/grid-bot.nomad
Labels: kind: enhancement, priority: deliverable, opsec: we-love-clean-code, area: ci-cd, opsec: ci-cd
